### ISSUE TITLE
Does not support workspace inheriting

### ISSUE THREAD

**Issue by clearloop** [bkchr/proc-macro-crate#34]
https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#inheriting-a-dependency-from-a-workspace

https://github.com/bkchr/proc-macro-crate/blob/1fdce5d354fdd73bbfb442820823a4b802254bd3/src/lib.rs#L179

```toml
[workspace.dependencies]
foo = { package = "bar" }
```

```toml
[dependencies]
foo = { workspace = true }
```

only iterated the dependencies inside the package, once a package renamed its dependency in workspace level, the searching logic doesn't work
