### ISSUE TITLE
Why Pin Dependency Versions?

### ISSUE THREAD

**Issue by westy92** [bkchr/proc-macro-crate#44]
I'm curious, why did you pin dependency versions instead of allowing updates to be used?

```toml
[dependencies]
toml_edit = "=0.20.2"
toml_datetime = "=0.6.3"
```

For example, `toml_edit`'s latest version is `0.21.0`, or `0.20.7` on the `0.20.x` line. Likewise, `0.6.5` is the latest version of  `toml_datetime`.

Upgrading `proc-macro-crate` just caused some of my dependencies to _downgrade_.
